import { Category } from '@/types';

export const categories: Category[] = [
  {
    title: 'SEO Tools',
    desc: 'Optimize your website for search engines.',
    path: '/seo-tools',
    icon: 'FaSearch',
    color: 'text-accent-blue',
    tools: [
      { title: 'Meta Tag Generator', desc: 'Create optimized meta tags.', path: '/seo-tools/meta-tag-generator', icon: 'FaTag' },
      { title: 'SERP Preview', desc: 'Preview your page in search results.', path: '/seo-tools/serp-preview', icon: 'FaEye' },
      { title: 'Keyword Density', desc: 'Analyze keyword usage in content.', path: '/seo-tools/keyword-density', icon: 'FaChartBar' },
      { title: 'Backlink Checker', desc: 'Analyze your website backlinks.', path: '/seo-tools/backlink-checker', icon: 'FaLink' },
      { title: 'SEO Audit Tool', desc: 'Perform a full SEO audit.', path: '/seo-tools/seo-audit-tool', icon: 'FaClipboardCheck' },
    ],
  },
  {
    title: 'Image Tools',
    desc: 'Edit and enhance your images.',
    path: '/image-tools',
    icon: 'FaImage',
    color: 'text-green-500',
    tools: [
      { title: 'Image Compressor', desc: 'Compress images for faster loading.', path: '/image-tools/image-compressor', icon: 'FaCompress' },
      { title: 'Resizer', desc: 'Resize images for web.', path: '/image-tools/resizer', icon: 'FaExpandArrowsAlt' },
      { title: 'Background Remover', desc: 'Remove backgrounds from images.', path: '/image-tools/background-remover', icon: 'FaEraser' },
      { title: 'Image to Text', desc: 'Extract text from images (OCR).', path: '/image-tools/image-to-text', icon: 'FaTextHeight' },
      { title: 'Watermark Tool', desc: 'Add watermarks to your images.', path: '/image-tools/watermark-tool', icon: 'FaStamp' },
    ],
  },
  {
    title: 'Video Tools',
    desc: 'Create and modify videos.',
    path: '/video-tools',
    icon: 'FaVideo',
    color: 'text-purple-500',
    tools: [
      { title: 'Trim Video', desc: 'Trim video files.', path: '/video-tools/trim-video', icon: 'FaCut' },
      { title: 'Convert to GIF', desc: 'Create GIFs from videos.', path: '/video-tools/convert-to-gif', icon: 'FaFilm' },
      { title: 'Extract Audio', desc: 'Extract audio from videos.', path: '/video-tools/extract-audio', icon: 'FaMusic' },
      { title: 'Video Compressor', desc: 'Compress video files.', path: '/video-tools/video-compressor', icon: 'FaCompress' },
      { title: 'Subtitle Generator', desc: 'Generate subtitles for videos.', path: '/video-tools/subtitle-generator', icon: 'FaClosedCaptioning' },
    ],
  },
  {
    title: 'PDF Tools',
    desc: 'Manage and convert PDF files.',
    path: '/pdf-tools',
    icon: 'FaFilePdf',
    color: 'text-red-500',
    tools: [
      { title: 'Merge PDFs', desc: 'Combine multiple PDFs.', path: '/pdf-tools/merge-pdfs', icon: 'FaPaperclip' },
      { title: 'Split PDF', desc: 'Split PDFs into parts.', path: '/pdf-tools/split-pdf', icon: 'FaScissors' },
      { title: 'PDF to Word', desc: 'Convert PDF to Word document.', path: '/pdf-tools/pdf-to-word', icon: 'FaFileWord' },
      { title: 'PDF to Image', desc: 'Convert PDFs to images.', path: '/pdf-tools/pdf-to-image', icon: 'FaImage' },
      { title: 'PDF Password Protector', desc: 'Add password protection to PDFs.', path: '/pdf-tools/pdf-password-protector', icon: 'FaLock' },
    ],
  },
  {
    title: 'Text Tools',
    desc: 'Manipulate and transform text.',
    path: '/text-tools',
    icon: 'FaFont',
    color: 'text-pink-500',
    tools: [
      { title: 'Case Converter', desc: 'Change letter casing.', path: '/text-tools/case-converter', icon: 'FaTextHeight' },
      { title: 'Word Counter', desc: 'Count words and characters.', path: '/text-tools/word-counter', icon: 'FaCalculator' },
      { title: 'Text Summarizer', desc: 'Summarize long text.', path: '/text-tools/text-summarizer', icon: 'FaCompressAlt' },
      { title: 'Text Diff Checker', desc: 'Compare differences between texts.', path: '/text-tools/text-diff-checker', icon: 'FaBalanceScale' },
      { title: 'Spell Checker', desc: 'Check spelling in your text.', path: '/text-tools/spell-checker', icon: 'FaCheckCircle' },
    ],
  },
  {
    title: 'Audio Tools',
    desc: 'Work with audio files.',
    path: '/audio-tools',
    icon: 'FaMusic',
    color: 'text-yellow-500',
    tools: [
      { title: 'MP3 Cutter', desc: 'Cut audio clips.', path: '/audio-tools/mp3-cutter', icon: 'FaCut' },
      { title: 'Audio Converter', desc: 'Convert audio files.', path: '/audio-tools/audio-converter', icon: 'FaSyncAlt' },
      { title: 'Noise Remover', desc: 'Remove noise from audio.', path: '/audio-tools/noise-remover', icon: 'FaFilter' },
      { title: 'Audio Merger', desc: 'Merge multiple audio files.', path: '/audio-tools/audio-merger', icon: 'FaPaperclip' },
      { title: 'Speed Changer', desc: 'Adjust audio playback speed.', path: '/audio-tools/speed-changer', icon: 'FaTachometerAlt' },
    ],
  },
  {
    title: 'Developer Tools',
    desc: 'Developer-focused utilities.',
    path: '/developer-tools',
    icon: 'FaCode',
    color: 'text-blue-600',
    tools: [
      { title: 'JSON Formatter', desc: 'Format and beautify JSON data.', path: '/developer-tools/json-formatter', icon: 'FaCode' },
      { title: 'JWT Decoder', desc: 'Decode JWT tokens.', path: '/developer-tools/jwt-decoder', icon: 'FaLockOpen' },
      { title: 'Regex Tester', desc: 'Test regular expressions.', path: '/developer-tools/regex-tester', icon: 'FaSearch' },
      { title: 'API Tester', desc: 'Test API endpoints.', path: '/developer-tools/api-tester', icon: 'FaPlug' },
      { title: 'CSS Minifier', desc: 'Minify CSS code.', path: '/developer-tools/css-minifier', icon: 'FaCompress' },
    ],
  },
  {
    title: 'Social Tools',
    desc: 'Enhance your social media presence.',
    path: '/social-tools',
    icon: 'FaShareSquare',
    color: 'text-indigo-500',
    tools: [
      { title: 'Instagram Bio Link', desc: 'Create a link for Instagram bio.', path: '/social-tools/instagram-bio-link', icon: 'FaLink' },
      { title: 'Hashtag Generator', desc: 'Generate trending hashtags.', path: '/social-tools/hashtag-generator', icon: 'FaHashtag' },
      { title: 'Caption AI', desc: 'Generate social media captions.', path: '/social-tools/caption-ai', icon: 'FaRobot' },
      { title: 'Post Scheduler', desc: 'Schedule social media posts.', path: '/social-tools/post-scheduler', icon: 'FaCalendarAlt' },
      { title: 'Engagement Analyzer', desc: 'Analyze post engagement.', path: '/social-tools/engagement-analyzer', icon: 'FaChartLine' },
    ],
  },
  {
    title: 'Color Tools',
    desc: 'Work with colors.',
    path: '/color-tools',
    icon: 'FaPalette',
    color: 'text-orange-500',
    tools: [
      { title: 'Color Picker', desc: 'Pick and preview colors.', path: '/color-tools/color-picker', icon: 'FaEyeDropper' },
      { title: 'Palette Generator', desc: 'Generate color palettes.', path: '/color-tools/palette-generator', icon: 'FaSwatchbook' },
      { title: 'Gradient Creator', desc: 'Create CSS gradients.', path: '/color-tools/gradient-creator', icon: 'FaPaintRoller' },
      { title: 'Color Blindness Simulator', desc: 'Simulate color blindness views.', path: '/color-tools/color-blindness-simulator', icon: 'FaEye' },
    ],
  },
  {
    title: 'Security Tools',
    desc: 'Secure your data and accounts.',
    path: '/security-tools',
    icon: 'FaShieldAlt',
    color: 'text-teal-500',
    tools: [
      { title: 'Password Generator', desc: 'Generate strong passwords.', path: '/security-tools/password-generator', icon: 'FaKey' },
      { title: 'Hash Checker', desc: 'Verify file hashes.', path: '/security-tools/hash-checker', icon: 'FaFingerprint' },
      { title: 'QR Auth Setup', desc: 'Set up QR-based authentication.', path: '/security-tools/qr-auth-setup', icon: 'FaQrcode' },
      { title: 'SSL Checker', desc: 'Check SSL certificates.', path: '/security-tools/ssl-checker', icon: 'FaCertificate' },
      { title: 'Two-Factor Auth Setup', desc: 'Set up 2FA for accounts.', path: '/security-tools/two-factor-auth-setup', icon: 'FaLock' },
    ],
  },
  {
    title: 'Markdown Tools',
    desc: 'Work with Markdown files.',
    path: '/markdown-tools',
    icon: 'FaMarkdown',
    color: 'text-gray-500',
    tools: [
      { title: 'Markdown to HTML', desc: 'Convert Markdown to HTML.', path: '/markdown-tools/markdown-to-html', icon: 'FaCode' },
      { title: 'Previewer', desc: 'Preview Markdown in real-time.', path: '/markdown-tools/previewer', icon: 'FaEye' },
      { title: 'Editor', desc: 'Edit Markdown with syntax highlighting.', path: '/markdown-tools/editor', icon: 'FaEdit' },
      { title: 'Markdown Table Generator', desc: 'Create Markdown tables.', path: '/markdown-tools/markdown-table-generator', icon: 'FaTable' },
    ],
  },
  {
    title: 'Encryption Tools',
    desc: 'Encrypt and decrypt data.',
    path: '/encryption-tools',
    icon: 'FaLock',
    color: 'text-cyan-500',
    tools: [
      { title: 'AES Encrypt/Decrypt', desc: 'Encrypt or decrypt with AES.', path: '/encryption-tools/aes-encrypt-decrypt', icon: 'FaLock' },
      { title: 'RSA Generator', desc: 'Generate RSA key pairs.', path: '/encryption-tools/rsa-generator', icon: 'FaKey' },
      { title: 'Base64 Encoder/Decoder', desc: 'Encode or decode Base64 data.', path: '/encryption-tools/base64-encoder-decoder', icon: 'FaCode' },
    ],
  },
  {
    title: 'File Tools',
    desc: 'Manage and process files.',
    path: '/file-tools',
    icon: 'FaFileAlt',
    color: 'text-blue-400',
    tools: [
      { title: 'Zip/Unzip Online', desc: 'Zip or unzip files.', path: '/file-tools/zip-unzip-online', icon: 'FaFileArchive' },
      { title: 'File Renamer', desc: 'Rename multiple files.', path: '/file-tools/file-renamer', icon: 'FaEdit' },
      { title: 'File Splitter', desc: 'Split large files into parts.', path: '/file-tools/file-splitter', icon: 'FaScissors' },
      { title: 'File Type Converter', desc: 'Convert files between formats.', path: '/file-tools/file-type-converter', icon: 'FaSyncAlt' },
    ],
  },
  {
    title: 'QR Code Tools',
    desc: 'Generate and read QR codes.',
    path: '/qr-code-tools',
    icon: 'FaQrcode',
    color: 'text-green-600',
    tools: [
      { title: 'QR Generator', desc: 'Generate QR codes from text.', path: '/qr-code-tools/qr-generator', icon: 'FaQrcode' },
      { title: 'QR Reader via Webcam', desc: 'Read QR codes using webcam.', path: '/qr-code-tools/qr-reader', icon: 'FaCamera' },
      { title: 'QR Code Styler', desc: 'Customize QR code appearance.', path: '/qr-code-tools/qr-code-styler', icon: 'FaPaintBrush' },
    ],
  },
  {
    title: 'Barcode Tools',
    desc: 'Generate and decode barcodes.',
    path: '/barcode-tools',
    icon: 'FaBarcode',
    color: 'text-purple-600',
    tools: [
      { title: 'Barcode Generator', desc: 'Generate barcodes.', path: '/barcode-tools/barcode-generator', icon: 'FaBarcode' },
      { title: 'UPC Decoder', desc: 'Decode UPC barcodes.', path: '/barcode-tools/upc-decoder', icon: 'FaSearch' },
      { title: 'Barcode Scanner', desc: 'Scan barcodes using webcam.', path: '/barcode-tools/barcode-scanner', icon: 'FaCamera' },
    ],
  },
  {
    title: 'Unit Converter',
    desc: 'Convert between different units.',
    path: '/unit-converter',
    icon: 'FaBalanceScale',
    color: 'text-indigo-600',
    tools: [
      { title: 'Length', desc: 'Convert lengths and distances.', path: '/unit-converter/length', icon: 'FaRuler' },
      { title: 'Mass', desc: 'Convert weights and masses.', path: '/unit-converter/mass', icon: 'FaWeight' },
      { title: 'Speed', desc: 'Convert speeds.', path: '/unit-converter/speed', icon: 'FaTachometerAlt' },
      { title: 'Time', desc: 'Convert time units.', path: '/unit-converter/time', icon: 'FaClock' },
      { title: 'Data', desc: 'Convert data sizes.', path: '/unit-converter/data', icon: 'FaDatabase' },
      { title: 'Temperature', desc: 'Convert temperatures.', path: '/unit-converter/temperature', icon: 'FaThermometerHalf' },
    ],
  },
  {
    title: 'Currency Tools',
    desc: 'Convert and analyze currencies.',
    path: '/currency-tools',
    icon: 'FaMoneyBillWave',
    color: 'text-teal-600',
    tools: [
      { title: 'Live Converter', desc: 'Convert currencies in real-time.', path: '/currency-tools/live-converter', icon: 'FaExchangeAlt' },
      { title: 'Historical Rates', desc: 'View historical exchange rates.', path: '/currency-tools/historical-rates', icon: 'FaHistory' },
      { title: 'Charts', desc: 'Visualize currency trends.', path: '/currency-tools/charts', icon: 'FaChartLine' },
      { title: 'Currency Calculator', desc: 'Calculate with exchange rates.', path: '/currency-tools/currency-calculator', icon: 'FaCalculator' },
    ],
  },
  {
    title: 'Timestamp Tools',
    desc: 'Work with timestamps and timezones.',
    path: '/timestamp-tools',
    icon: 'FaClock',
    color: 'text-orange-600',
    tools: [
      { title: 'Epoch Converter', desc: 'Convert timestamps to human-readable dates.', path: '/timestamp-tools/epoch-converter', icon: 'FaCalendarAlt' },
      { title: 'Timezone Diff', desc: 'Calculate timezone differences.', path: '/timestamp-tools/timezone-diff', icon: 'FaGlobe' },
      { title: 'Countdown Timer', desc: 'Create countdown timers.', path: '/timestamp-tools/countdown-timer', icon: 'FaHourglassHalf' },
    ],
  },
  {
    title: 'AI Tools',
    desc: 'Leverage AI for productivity.',
    path: '/ai-tools',
    icon: 'FaRobot',
    color: 'text-blue-500',
    tools: [
      { title: 'Text to Image', desc: 'Generate images from text prompts.', path: '/ai-tools/text-to-image', icon: 'FaImage' },
      { title: 'Summarizer', desc: 'Summarize text using AI.', path: '/ai-tools/summarizer', icon: 'FaCompressAlt' },
      { title: 'Chatbot UI', desc: 'Interact with an AI chatbot.', path: '/ai-tools/chatbot-ui', icon: 'FaCommentDots' },
      { title: 'Sentiment Analyzer', desc: 'Analyze text sentiment with AI.', path: '/ai-tools/sentiment-analyzer', icon: 'FaSmile' },
    ],
  },
  {
    title: 'UX Tools',
    desc: 'Enhance user experience design.',
    path: '/ux-tools',
    icon: 'FaUserAlt',
    color: 'text-pink-600',
    tools: [
      { title: 'Lorem Ipsum Generator', desc: 'Generate placeholder text.', path: '/ux-tools/lorem-ipsum-generator', icon: 'FaFont' },
      { title: 'Skeleton UI Maker', desc: 'Create skeleton UI for loading states.', path: '/ux-tools/skeleton-ui-maker', icon: 'FaSpinner' },
      { title: 'Wireframe Generator', desc: 'Generate wireframes for UI design.', path: '/ux-tools/wireframe-generator', icon: 'FaDraftingCompass' },
    ],
  },
  {
    title: 'HTML Tools',
    desc: 'Work with HTML code.',
    path: '/html-tools',
    icon: 'FaHtml5',
    color: 'text-red-600',
    tools: [
      { title: 'Minifier', desc: 'Minify HTML code.', path: '/html-tools/minifier', icon: 'FaCompress' },
      { title: 'Beautifier', desc: 'Beautify HTML code.', path: '/html-tools/beautifier', icon: 'FaCode' },
      { title: 'Validator', desc: 'Validate HTML syntax.', path: '/html-tools/validator', icon: 'FaCheckCircle' },
      { title: 'HTML to Markdown', desc: 'Convert HTML to Markdown.', path: '/html-tools/html-to-markdown', icon: 'FaMarkdown' },
    ],
  },
  {
    title: 'Email Tools',
    desc: 'Tools for email management.',
    path: '/email-tools',
    icon: 'FaEnvelope',
    color: 'text-green-400',
    tools: [
      { title: 'Temp Email', desc: 'Generate temporary email addresses.', path: '/email-tools/temp-email', icon: 'FaEnvelopeOpen' },
      { title: 'Subject Line Tester', desc: 'Test email subject lines.', path: '/email-tools/subject-line-tester', icon: 'FaQuestionCircle' },
      { title: 'Email Signature Generator', desc: 'Create professional email signatures.', path: '/email-tools/email-signature-generator', icon: 'FaSignature' },
    ],
  },
  {
    title: 'Favicon Tools',
    desc: 'Create and manage favicons.',
    path: '/favicon-tools',
    icon: 'FaIcons',
    color: 'text-purple-400',
    tools: [
      { title: 'Favicon Generator', desc: 'Generate favicons for websites.', path: '/favicon-tools/favicon-generator', icon: 'FaIcons' },
      { title: 'iOS Icon Creator', desc: 'Create icons for iOS apps.', path: '/favicon-tools/ios-icon-creator', icon: 'FaApple' },
      { title: 'Android Icon Creator', desc: 'Create icons for Android apps.', path: '/favicon-tools/android-icon-creator', icon: 'FaAndroid' },
    ],
  },
  {
    title: 'JSON Tools',
    desc: 'Work with JSON data.',
    path: '/json-tools',
    icon: 'FaFileCode',
    color: 'text-yellow-600',
    tools: [
      { title: 'Viewer', desc: 'View JSON data in a tree structure.', path: '/json-tools/viewer', icon: 'FaEye' },
      { title: 'Formatter', desc: 'Format JSON data.', path: '/json-tools/formatter', icon: 'FaCode' },
      { title: 'Comparator', desc: 'Compare two JSON files.', path: '/json-tools/comparator', icon: 'FaBalanceScale' },
      { title: 'JSON to CSV', desc: 'Convert JSON to CSV format.', path: '/json-tools/json-to-csv', icon: 'FaFileCsv' },
    ],
  },
  {
    title: 'GIF Tools',
    desc: 'Create and edit GIFs.',
    path: '/gif-tools',
    icon: 'FaFilm',
    color: 'text-teal-400',
    tools: [
      { title: 'Resize GIF', desc: 'Resize animated GIFs.', path: '/gif-tools/resize-gif', icon: 'FaExpandArrowsAlt' },
      { title: 'Optimize', desc: 'Optimize GIF file size.', path: '/gif-tools/optimize', icon: 'FaCompress' },
      { title: 'Reverse GIF', desc: 'Reverse GIF animations.', path: '/gif-tools/reverse-gif', icon: 'FaUndo' },
      { title: 'GIF Frame Extractor', desc: 'Extract frames from GIFs.', path: '/gif-tools/gif-frame-extractor', icon: 'FaImages' },
    ],
  },
];