import { InternalToolConfig } from '../../types/toolTypes';
import { categories } from '../../types/categories';
import { templates } from './templates';

export const seoTools: InternalToolConfig[] = [
  {
    category: categories.SEO,
    slug: 'meta-tag-generator',
    title: 'Meta Tag Generator',
    shortDescription: 'Create optimized meta tags.',
    longDescription: 'Create optimized meta tags for SEO, including title, description, and Open Graph tags.',
    icon: 'FaTag',
    template: 'TextToolTemplate', // or whatever template is appropriate
    keywords: ['meta', 'tags', 'SEO', 'HTML'],
    id: 'seo-meta-tag-generator',
    tags: ['seo', 'meta', 'tags'],
    isHidden: false,
    isExperimental: false,
    logicLoader: async () => import('../../tools/seoTools').then(mod => mod.metaTagGenerator),
    props: { inputType: 'text', resultType: 'text' },
  },
  {
    category: categories.SEO,
    slug: 'serp-preview',
    title: 'SERP Preview',
    shortDescription: 'Preview your page in search results.',
    longDescription: 'Preview how your page will look in Google search results, including title, description, and URL.',
    icon: 'FaEye',
    template: 'TextToolTemplate',
    keywords: ['SEO', 'preview', 'SERP'],
    id: 'seo-serp-preview',
    tags: ['seo', 'preview'],
    isHidden: false,
    isExperimental: false,
    logicLoader: async () => import('../../tools/seoTools').then(mod => mod.serpPreview),
    props: { inputType: 'text', resultType: 'text' },
  },
  {
    category: categories.SEO,
    slug: 'keyword-density',
    title: 'Keyword Density',
    shortDescription: 'Analyze keyword usage in content.',
    longDescription: 'Analyze the frequency and density of keywords in your text content to improve SEO optimization.',
    icon: 'FaChartBar',
    template: 'TextToolTemplate',
    keywords: ['SEO', 'keywords', 'density'],
    id: 'seo-keyword-density',
    tags: ['seo', 'keywords'],
    isHidden: false,
    isExperimental: false,
    logicLoader: async () => import('../../tools/seoTools').then(mod => mod.keywordDensity),
    props: { inputType: 'text', resultType: 'table' },
  },
  {
    category: categories.SEO,
    slug: 'backlink-checker',
    title: 'Backlink Checker',
    shortDescription: 'Analyze your website backlinks.',
    longDescription: 'Check all backlinks pointing to your website and analyze their quality and SEO impact.',
    icon: 'FaLink',
    template: 'TextToolTemplate',
    keywords: ['SEO', 'backlinks', 'links'],
    id: 'seo-backlink-checker',
    tags: ['seo', 'backlinks'],
    isHidden: false,
    isExperimental: false,
    logicLoader: async () => import('../../tools/seoTools').then(mod => mod.backlinkChecker),
    props: { inputType: 'text', resultType: 'table' },
  },
  {
    category: categories.SEO,
    slug: 'seo-audit-tool',
    title: 'SEO Audit Tool',
    shortDescription: 'Perform a full SEO audit.',
    longDescription: 'Run a comprehensive SEO audit on your website, checking technical SEO, content, backlinks, and on-page factors.',
    icon: 'FaClipboardCheck',
    template: 'TextToolTemplate',
    keywords: ['SEO', 'audit', 'website'],
    id: 'seo-audit-tool',
    tags: ['seo', 'audit'],
    isHidden: false,
    isExperimental: false,
    logicLoader: async () => import('../../tools/seoTools').then(mod => mod.seoAuditTool),
    props: { inputType: 'text', resultType: 'table' },
  },
];